version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: '📌 '
  - package-ecosystem: npm
    directory: /functions
    schedule:
      interval: daily
    commit-message:
      prefix: '📌(functions) '
