root: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:n/recommended
  - google
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
  - plugin:astro/recommended
  - plugin:svelte/recommended
  - plugin:svelte/prettier
plugins:
  - import
  - prettier
  - '@typescript-eslint'
env:
  browser: true
  node: true
  es6: true
  es2017: true
  es2020: true
parserOptions:
  parser: '@typescript-eslint/parser'
  ecmaVersion: 2022
  sourceType: module
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
      - .tsx
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.json
  svelte3/typescript: true
overrides:
  - files:
      - '*.astro'
    parser: astro-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions:
        - '*.astro'
  - files:
      - '*.svelte'
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
rules:
  n/no-missing-import: off
  n/no-unpublished-import: off
  n/no-unsupported-features/node-builtins: off
  svelte/valid-compile: warn
  # Breaks Svelte imports, until https://github.com/import-js/eslint-plugin-import/issues/1479 is resolved
  import/namespace: off
  import/no-duplicates: off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-unused-vars':
    # Allow unused vars starting with _, for quick iterators
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  import/no-unresolved:
    - error
    - ignore:
        - 'virtual:pwa-info'
        - 'virtual:pwa-register'
