name: "\U0001F41E Bug report"
description: Report an issue with ChromeOS.dev. To report an issue with ChromeOS, see the "Report a ChromeOS problem or send feedback" link below
labels: ["problem: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This form should only be used to file bugs for ChromeOS.dev, our developer documentation and news site. If you're looking to report a bug for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead, or [report a ChromeOS bug](https://www.chromium.org/chromium-os/developer-library/guides/bugs/reporting-bugs/) directly.
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide clear steps to reproduce the bug you're seeing.
      placeholder: |
        Steps to reproduce the behavior:

        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser context
      description: Browser, browser version, operating system, and optional device. Please include if reporting a site bug.
      placeholder: Chrome 124 on ChromeOS 124, Google Pixelbook
      validation:
        required: false
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --binaries --browsers`. Please include if reporting a development bug.
      render: shell
      placeholder: System, Binaries, Browsers
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Follow our [Code of Conduct](https://github.com/chromeos/chromeos.dev/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: Read the [Contributing Guidelines](https://github.com/chromeos/chromeos.dev/blob/main/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/chromeos/chromeos.dev/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Make sure this is a ChromeOS.dev (the ChromeOS documentation and news site) issue and not a general ChromeOS issue. If you're looking to report a bug for ChromeOS, please [report a ChromeOS problem or send feedback](https://support.google.com/chromebook/answer/2982029?hl=en) instead.
          required: true
        - label: Check that this is a concrete bug. For Q&A, either ask in the [Chromebook Help Community](https://support.google.com/chromebook/community?sjid=4749359234014638826-NA) or join the `#chromeos` or `#chromeos-forum` channels in the [Google Developer Community Discord](https://discord.gg/google-dev-community).
          required: true
        - label: You've included either your browser context or system info, depending on what type of bug you're filing.
          required: true
